default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= Rails.application.credentials[:db_user] %>
  password: <%= Rails.application.credentials[:db_password] %>

development:
  <<: *default
  database: pub_crawl_development

test:
  <<: *default
  database: pub_crawl_test

production:
  <<: *default
  database: pub_crawl_production
  username: pub_crawl
  password: <%= ENV["PUB_CRAWL_DATABASE_PASSWORD"] %>
